kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/openshift-instruqt/blog-django-py'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"blog-django-py2:latest","namespace":"fiap"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blog-django-py2\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  name: blog-django-py2
  namespace: fiap
spec:
  selector:
    matchLabels:
      app: blog-django-py2
  template:
    metadata:
      labels:
        app: blog-django-py2
        deploymentconfig: blog-django-py2
    spec:
      containers:
        - name: blog-django-py2
          image: >-
            image-registry.openshift-image-registry.svc:5000/fiap/blog-django-py2@sha256:e7a44cf50a9bd6238b8ab7887a7fe8173aa3d9cb2e382fcddc9b25b9968efaad
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler